service: infra
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  deploymentMethod: direct
  region: ap-south-1
  deploymentPrefix: infra

  Resources:
    - ${file(./resources/ec2.yml)}
