service: infra
frameworkVersion: '3'
configValidationMode: error
plugins:
  - serverless-deployment-bucket
  - serverless-plugin-resource-tagging
provider:
  name: aws
  deploymentMethod: direct
  region: ap-south-1
  deploymentPrefix: infra
  deploymentBucket: infra-bucket

  resources:
    - ${file(./resources/ec2.yml)}
