---
MyEC2Instance: 
  Type: AWS::EC2::Instance
  Properties: 
    ImageId: "ami-012b9156f755804f5"
      KeyName: "testkey"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "false"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}